# Generated by Django 4.2.6 on 2023-11-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='Song_Name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='Upload_File',
        ),
    ]
