# Generated by Django 4.2.6 on 2023-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='img/sampleaudio.mp3'),
        ),
    ]
